server:
  port: 9000

spring:
  application:
    name: coss4-api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.59:8000/eureka/

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 1000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

zuul:
  prefix: /coss4
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 10000
  routes:
    competition-management:
      path: /competition-management/**
      serviceId: eureka-client-competition-management
      strip-prefix: false
    system-dictionary:
      path: /system-dictionary/**
      serviceId: eureka-client-system-dictionary
      strip-prefix: false
    user-management:
      path: /user-management/**
      serviceId: eureka-client-user-management
      strip-prefix: false
    verification-code:
      path: /verification-code/**
      serviceId: eureka-client-verification-code
      strip-prefix: false
  sensitive-headers:
