server:
  port: 8803
  servlet:
    context-path: /user-management

spring:
  application:
    name: eureka-client-user-management
  datasource:
    username: coss_user
    password: MysqlCossuser123Cloud!@#
    url: jdbc:mysql://139.199.36.160:3306/coss_dev?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: cn.net.powerinv.coss4.entity
