server:
  port: 8802
  servlet:
    context-path: /verification-code

spring:
  application:
    name: eureka-client-verification-code

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
